spring.application.name=pcms
server.servlet.context-path=/pcms
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/pcms_v2
spring.datasource.username=pcmsuser
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Spring Boot Devtools Settings
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
